<?php
namespace app\home\controller;


use app\home\model\MusicModel;
use think\Controller;

class Base extends Controller{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //音乐文件查询
        $music = new MusicModel();
        $music_list = $music->getList('id,title,singer artist,music_path mp3,img_path cover');
        foreach($music_list as &$v){
            $v['mp3'] = 'http://'.$v['mp3'];
            $v['cover'] = BLOG . $v['cover'];
        }
        $music_list = json_encode($music_list);
        $this->assign('music_list',$music_list);
    }
}